# Generated by Django 4.1 on 2022-11-03 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='entrenamiento_admision',
            field=models.BooleanField(verbose_name='Entrenamiento del personal'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='estado_herramientas',
            field=models.BooleanField(verbose_name='Herramientas'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='estado_materiales',
            field=models.BooleanField(verbose_name='Materiales'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='instalaciones_electricas',
            field=models.BooleanField(verbose_name='Instalaciones electricas'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='instalaciones_sanitarias',
            field=models.BooleanField(verbose_name='Instalaciones sanitarias'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='validez_extintores',
            field=models.BooleanField(verbose_name='Validez extintores'),
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_termino', models.DateField(verbose_name='Fecha Termino')),
                ('visitas_mes', models.CharField(max_length=45, verbose_name='Visitas por mes')),
                ('asesorias_mes', models.CharField(max_length=45, verbose_name='Asesorias por mes')),
                ('capacitaciones_mes', models.CharField(max_length=45, verbose_name='Capacitaciones por mes')),
                ('Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
